spring:
    application:
        name: ledger-service

    datasource:
        url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Seoul
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: hwryu990927!

    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
#        open-in-view: false
        show-sql: true
        hibernate:
            default_batch_fetch_size: 100
            ddl-auto: create
        defer-datasource-initialization: true
        properties:
            hibernate:
                jdbc:
                    batch_size: 25
                    batch_versioned_data: true
                    order_inserts: true
                    order_updates: true
                    batch_fetch_size: 500
